name: CI Build & Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity check
        run: |
          echo "Rodando CI..."
          ls -la
      - name: Unit tests (placeholder)
        run: |
          echo "Sem testes reais ainda — passando :)"
